## Import

Lorem ipsum dolor sit amet.

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import os
import librosa
import librosa.display
import scipy
from scipy.io import wavfile
from scipy.signal import butter, filtfilt
from scipy.signal import stft
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense

## Nahrání signálu

Lorem ipsum dolor sit amet.

In [6]:
# NEZAPOMENOUT ŘEŠIT OBA KANÁLY

class Instrument:
    def __init__(self, name, directory) -> None:
        self.name = name
        self.directory = directory
        self.wav_files = [file for file in os.listdir(directory) if file.endswith('.wav')]
        self.signals_raw = {}
        self.signals_envelope = {}
        self.signals_spectogram = {}
        self._load_signals()

    def _load_signals(self):
        for wav_file in self.wav_files:
            file_path = os.path.join(self.directory, wav_file)
            sample_rate, data = wavfile.read(file_path)
            self.signals_raw[wav_file] = (sample_rate, data) # Store the sample rate and signal data as a tuple (sample_rate, data)
    

all_instrument_classes = []

all_instrument_classes.append(Instrument("cello", "Dataset\\cel"))
all_instrument_classes.append(Instrument("clarinet", "Dataset\\cla"))
all_instrument_classes.append(Instrument("flute", "Dataset\\flu"))
all_instrument_classes.append(Instrument("guitar_acoustic", "Dataset\\gac"))
all_instrument_classes.append(Instrument("guitar_electric", "Dataset\\gel"))
all_instrument_classes.append(Instrument("organ", "Dataset\\org"))
all_instrument_classes.append(Instrument("piano", "Dataset\\pia"))
all_instrument_classes.append(Instrument("saxophone", "Dataset\\sax"))
all_instrument_classes.append(Instrument("trumpet", "Dataset\\tru"))
all_instrument_classes.append(Instrument("violin", "Dataset\\vio"))
all_instrument_classes.append(Instrument("voice", "Dataset\\voi"))



## Očištění a sjednocení signálu

Lorem ipsum dolor sit amet.

In [ ]:
# NEZAPOMENOUT ŘEŠIT OBA KANÁLY

# Sjednocení
## Všechna trénovací data mají stejný sample_rate(44100) i délku(3s) i data_shape(132299, 2), takže není třeba sjednocovat.

# Očištění
# Audio je kvalitní a žádné závažné problémy, které by bylo třeba odstranit

## Amplitude envelope

Lorem ipsum dolor sit amet.

In [7]:
# RMS (Root Mean Square) Envelope, because i found it is best for continuous sounds (instruments)
def amplitude_envelope(signal, sample_rate, window_size=0.05):
    window_size_in_samples = int(window_size * sample_rate)
    envelope = []
    for i in range(0, len(signal), window_size_in_samples):
        window = signal[i:i + window_size_in_samples]
        rms = np.sqrt(np.mean(window**2)) if len(window) > 0 else 0
        envelope.append(rms)
    return np.array(envelope)


for instrument in all_instrument_classes:
    for wav_file, (sample_rate, signal) in instrument.signals_raw.items():
        instrument.signals_envelope[wav_file] = amplitude_envelope(signal, sample_rate)

C:\Users\popa4\AppData\Local\Temp\ipykernel_11932\1640000231.py:7: RuntimeWarning: invalid value encountered in sqrt
  rms = np.sqrt(np.mean(window**2)) if len(window) > 0 else 0


## Spectrogram

Lorem ipsum dolor sit amet.

In [12]:
# spectrogram se počítá skrz sFT (frekvence místo amplitudy, neural network mňamuje)
'''
Přes librosu to nejde, divný dependencies na starší verze numpy + mel spectogram vzdávám, blbne to
'''

def create_spectrogram(signal, sample_rate, nperseg=1024):
    frequencies, times, spectrogram = stft(signal, fs=sample_rate, nperseg=nperseg)
    return np.abs(spectrogram)

for instrument in all_instrument_classes:
    for wav_file, (sample_rate, signal) in instrument.signals_raw.items():
        instrument.signals_spectogram[wav_file] = create_spectrogram(signal, sample_rate)

c:\Users\popa4\OneDrive\Dokumenty\GitHub\USU-IRMAS-instrument-recognition\.venv\Lib\site-packages\scipy\signal\_spectral_py.py:1240: UserWarning: nperseg = 1024 is greater than input length  = 2, using nperseg = 2
  freqs, time, Zxx = _spectral_helper(x, x, fs, window, nperseg, noverlap,


## Neural network

Lorem ipsum dolor sit amet.

In [15]:
# x_train = signal
# y_train = instrument

# model = Sequential()
# model.add(Dense(units=32, activation='Leaky ReLU'))



[[[ 82.  30.   0.]
  [ 82.  30.   0.]]

 [[ 73.  40.   0.]
  [ 73.  40.   0.]]

 [[ 62.  49.   0.]
  [ 62.  49.   0.]]

 ...

 [[100. 141.   0.]
  [100. 141.   0.]]

 [[ 89. 153.   0.]
  [ 89. 153.   0.]]

 [[ 78. 163.   0.]
  [ 78. 163.   0.]]]
